# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-03 21:37
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NauUserExtendedModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_authorization",
                    models.BooleanField(
                        default=False,
                        verbose_name="I authorize data processing for this site ",
                    ),
                ),
                (
                    "citizen_card",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        null=True,
                        verbose_name="Citizen Card",
                    ),
                ),
                (
                    "nif",
                    models.CharField(
                        blank=True, max_length=9, null=True, verbose_name="NIF"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
