# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-26 21:32
from __future__ import absolute_import, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nau_openedx_extensions", "0002_auto_20190514_1802"),
    ]

    operations = [
        migrations.AddField(
            model_name="nauuserextendedmodel",
            name="cc_nic_check_digit",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="NIC Check Digit"
            ),
        ),
    ]
