# Generated by Django 2.2.16 on 2021-02-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nau_openedx_extensions', '0005_nauuserextendedmodel_allow_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nauuserextendedmodel',
            name='employment_situation',
            field=models.TextField(blank=True, choices=[('Student', 'Student'), ('Unemployed', 'Unemployed'), ('Public service contract', 'Public service contract'), ('Private institution contract', 'Private institution contract'), ('Self employed entrepreneur', 'Self employed entrepreneur'), ('Other', 'Other')], null=True, verbose_name='Employment situation'),
        ),
    ]
