# Generated by Django 2.2.16 on 2022-02-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0033_userprofile_state'),
        ('nau_openedx_extensions', '0006_auto_20210215_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAccessRoleProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('student.courseaccessrole',),
        ),
        migrations.AddField(
            model_name='nauuserextendedmodel',
            name='nif',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='NIF'),
        ),
        migrations.AlterField(
            model_name='nauuserextendedmodel',
            name='cc_birth_date',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='CC Birth date'),
        ),
        migrations.AlterField(
            model_name='nauuserextendedmodel',
            name='cc_doc_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='CC Document number'),
        ),
        migrations.AlterField(
            model_name='nauuserextendedmodel',
            name='cc_first_name',
            field=models.TextField(blank=True, null=True, verbose_name='CC First name'),
        ),
        migrations.AlterField(
            model_name='nauuserextendedmodel',
            name='cc_last_name',
            field=models.TextField(blank=True, null=True, verbose_name='CC Last name'),
        ),
        migrations.AlterField(
            model_name='nauuserextendedmodel',
            name='cc_nationality',
            field=models.TextField(blank=True, null=True, verbose_name='CC Nacionality'),
        ),
        migrations.AlterField(
            model_name='nauuserextendedmodel',
            name='cc_nic',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='CC NIC'),
        ),
        migrations.AlterField(
            model_name='nauuserextendedmodel',
            name='cc_nic_check_digit',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='CC NIC Check Digit'),
        ),
        migrations.AlterField(
            model_name='nauuserextendedmodel',
            name='cc_nif',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CC NIF'),
        ),
        migrations.AlterField(
            model_name='nauuserextendedmodel',
            name='cc_zip3',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='CC Zip code 3 digits'),
        ),
        migrations.AlterField(
            model_name='nauuserextendedmodel',
            name='cc_zip4',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='CC Zip code 4 digits'),
        ),
    ]
