# Generated by Django 3.2.16 on 2024-04-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nau_openedx_extensions', '0007_auto_20220223_1158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseAccessRoleProxy',
        ),
        migrations.AlterField(
            model_name='nauuserextendedmodel',
            name='data_authorization',
            field=models.BooleanField(default=False, verbose_name="I have read and understood the <a href='https://www.nau.edu.pt/legal/politica-de-privacidade/' rel='noopener' target='_blank'>Privacy Policy</a>"),
        ),
    ]
