# Generated by Django 4.2.23 on 2025-10-19 14:56

import uuid

from django.db import migrations, models

import nau_openedx_extensions.partner_integration.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('nau_openedx_extensions', '0008_rename_data_authorization'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerAPIClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('query_security_scope', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='partner_clients', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='partner_client_permissions', to='auth.permission')),
            ],
        ),
    ]
