# Generated by Django 4.2.23 on 2025-12-11 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import nau_openedx_extensions.custom_registration_form.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nau_openedx_extensions', '0009_partnerapiclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSOPartnerIntegration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_user_id', models.CharField(max_length=128)),
                ('partner_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nau_openedx_extensions.partnerapiclient')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'external_user_id')},
            },
        ),
    ]
