# Generated by Django 4.2.20 on 2026-03-18 10:13

from django.db import migrations, models

import nau_openedx_extensions.custom_registration_form.models


class Migration(migrations.Migration):

    dependencies = [
        ('nau_openedx_extensions', '0010_ssopartnerintegration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ssopartnerintegration',
            unique_together=set(),
        ),
    ]
