# Generated by Django 4.2.20 on 2026-07-20 12:06

from django.db import migrations, models
from django.utils import timezone

import nau_openedx_extensions.custom_registration_form.models


class Migration(migrations.Migration):

    dependencies = [
        ('nau_openedx_extensions', '0012_naucoursefilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssopartnerintegration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, default=None),
        ),
        migrations.AddField(
            model_name='ssopartnerintegration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=timezone.now),
        ),
    ]
