# Generated by Django 4.2.20 on 2026-08-15 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nau_openedx_extensions', '0013_ssopartnerintegration_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssopartnerintegration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='ssopartnerintegration',
            constraint=models.UniqueConstraint(fields=('user', 'partner_client'), name='unique_sso_link_per_user_and_partner_client'),
        ),
        migrations.AddConstraint(
            model_name='ssopartnerintegration',
            constraint=models.UniqueConstraint(fields=('partner_client', 'external_user_id'), name='unique_sso_link_per_partner_client_and_external_user'),
        ),
    ]
