NAU_SEND_COURSE_CERTIFICATE_CONFIG:
  - service_name: portugal_digital
    endpoint_url: https://academiaportugaldigital.pt/api/api/Course/FinishedIntegrationNau
    auth_token: XXXXXXXXXXXXXXXXXXXXX
    auth_type: bearer
    auth_header: Authorization
    page_size: 100
    days: 30
    fields:
      - name: key
        func: nau_openedx_extensions.coursecertificate.extractors.student.email
        trans: md5
      - name: value
        func: nau_openedx_extensions.coursecertificate.extractors.course.id

  - service_name: ina_recap
    endpoint_url: https://ina.gov.pt/api/v1/certificates/recap-integration
    auth_token: XXXXXXXXXXXXXXXXXXXXX
    auth_type: bearer
    auth_header: Authorization
    page_size: 2
    days: 50
    fields:
      - name: email
        func: nau_openedx_extensions.coursecertificate.extractors.student.email
      - name: username
        func: nau_openedx_extensions.coursecertificate.extractors.student.username
      - name: name
        func: nau_openedx_extensions.coursecertificate.extractors.student.name
      - name: nif
        func: nau_openedx_extensions.coursecertificate.extractors.student.nau_user_extended_model_field
        args: nif
      - name: enrolled_date
        func: nau_openedx_extensions.coursecertificate.extractors.student.enrolled_date
      - name: certificate_date
        func: nau_openedx_extensions.coursecertificate.extractors.certificate.date
      - name: certificate_url
        func: nau_openedx_extensions.coursecertificate.extractors.certificate.url
      - name: course_id
        func: nau_openedx_extensions.coursecertificate.extractors.course.id
      - name: course_code
        func: nau_openedx_extensions.coursecertificate.extractors.course.code
      - name: course_name
        func: nau_openedx_extensions.coursecertificate.extractors.course.name
    filters:
      - func: nau_openedx_extensions.coursecertificate.filters.certificate_by_course_id_regex
        args: course-v1
      - func: nau_openedx_extensions.coursecertificate.filters.certificate_by_org
        args: EduNext
