NAU_SEND_COURSE_CERTIFICATE_CONFIG:
  - service_name: portugal_digital
    endpoint_url: https://academiaportugaldigital.pt/api/api/Course/FinishedIntegrationNau
    endpoint_timeout: 60
    auth_token: XXXXXXXXXXXXXXXXXXXXX
    auth_type: bearer
    auth_header: Authorization
    page_size: 100
    days: 30
    fields:
      - name: key
        func: nau_openedx_extensions.coursecertificate.extractors.student_email
        trans: md5
      - name: value
        func: nau_openedx_extensions.coursecertificate.extractors.course_id

  - service_name: ina_recap
    endpoint_url: https://ina.gov.pt/api/v1/certificates/recap-integration
    endpoint_timeout: 60
    auth_token: XXXXXXXXXXXXXXXXXXXXX
    auth_type: bearer
    auth_header: Authorization
    page_size: 500
    days: 50
    fields:
      - name: email
        func: nau_openedx_extensions.coursecertificate.extractors.student_email
      - name: username
        func: nau_openedx_extensions.coursecertificate.extractors.student_username
      - name: name
        func: nau_openedx_extensions.coursecertificate.extractors.student_name
      - name: nif
        func: nau_openedx_extensions.coursecertificate.extractors.student_nau_user_extended_model_field
        args: nif
      - name: enrolled_date
        func: nau_openedx_extensions.coursecertificate.extractors.student_enrolled_date
      - name: certificate_date
        func: nau_openedx_extensions.coursecertificate.extractors.certificate_date
      - name: certificate_url
        func: nau_openedx_extensions.coursecertificate.extractors.certificate_url
      - name: course_id
        func: nau_openedx_extensions.coursecertificate.extractors.course_id
      - name: course_code
        func: nau_openedx_extensions.coursecertificate.extractors.course_code
      - name: course_name
        func: nau_openedx_extensions.coursecertificate.extractors.course_name
    filters:
      - func: nau_openedx_extensions.coursecertificate.filters.certificate_by_course_id_regex
        args: course-v1
      - func: nau_openedx_extensions.coursecertificate.filters.certificate_by_org
        args: EduNext
