name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - .*master.*


jobs:
  create-virtualenv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
    - uses: syphar/restore-virtualenv@v1
      id: cache-virtualenv

    - uses: syphar/restore-pip-download-cache@v1
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'

    - run: pip install -r requirements/test.txt
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'

  # linter:
  #   needs: create-virtualenv
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v1
  #   - uses: actions/setup-python@v2
  #   - uses: syphar/restore-virtualenv@v1
  #     id: cache-virtualenv

  #   - run: make quality

  tests:
    needs: create-virtualenv
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
    - uses: syphar/restore-virtualenv@v1
      id: cache-virtualenv

    - run: make python-test
