# Generated by Django 4.2.13 on 2025-08-27 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentAllowedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code to identify this allowed list', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this allowed list')),
                ('custom_exception_message', models.TextField(blank=True, help_text='Custom message to show when enrollment is blocked. If empty, uses default message.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Enrollment Allowed List',
                'verbose_name_plural': 'Enrollment Allowed Lists',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentAllowedDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text="Domain name (e.g., 'example.com')", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allowed_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='enrollment_by_domain.enrollmentallowedlist')),
            ],
            options={
                'verbose_name': 'Enrollment Allowed Domain',
                'verbose_name_plural': 'Enrollment Allowed Domains',
                'ordering': ['domain'],
                'unique_together': {('allowed_list', 'domain')},
            },
        ),
    ]
